name: second_coopre
root_dir: '/data/zhihaoz/v2xreal/v2xreal/train'
validate_dir: '/data/zhihaoz/v2xreal/v2xreal/test'
dataset_mode: 'vc' #vc, ic, v2v, i2i

yaml_parser: "load_second_params"

wild_setting:
  async: false
  async_overhead: 60
  seed: 20
  loc_err: false
  xyz_std: 0.2
  ryp_std: 0.2

train_params:
  batch_size: &batch_size 1
  epoches: &epoches 15
  eval_freq: 1
  save_freq: 1
  max_cav: 4 #7

fusion:
  core_method: 'EarlyFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.1, 0.1, 0.2]
    max_points_per_voxel: 5
    max_voxel_train: 128000
    max_voxel_test: 70000
  bev_args: 
    voxel_size: [0.8, 0.8, 8.0]
    max_points_per_voxel: 64 #30
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -40, -5, 140.8, 40, 3]
  num_class: &num_class 3
  anchor_generator_config: &anchor_generator_config
    - 'class_name': 'vehicle'
      'anchor_sizes': [ [3.9, 1.6, 1.56]]
      'anchor_rotations': [ 0, 1.57]
      'anchor_bottom_heights': [-1.78]
      'align_center': True 
      'feature_map_stride': 8
      'matched_threshold': 0.6
      'unmatched_threshold': 0.45
    - 'class_name': 'pedestrian'
      'anchor_sizes': [ [0.8, 0.6, 1.73]]
      'anchor_rotations': [ 0, 1.57]
      'anchor_bottom_heights': [-0.6]
      'align_center': True 
      'feature_map_stride': 8
      'matched_threshold': 0.5
      'unmatched_threshold': 0.35
    - 'class_name': 'truck'
      'anchor_sizes': [ [8, 3, 3]]
      'anchor_rotations': [ 0, 1.57]
      'anchor_bottom_heights': [-1.78]
      'align_center': True 
      'feature_map_stride': 8
      'matched_threshold': 0.6
      'unmatched_threshold': 0.45

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    num: &achor_num 2
    anchor_generator_config: *anchor_generator_config
  target_args:
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 300 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: second_coopre
  args:
    batch_size: *batch_size
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    num_class: *num_class
    mean_vfe:
      feature_points: 4

    backbone_3d:
      mask_ratio: 0.7
      down_factor: 8
      grid: 1
      voxel_size: *voxel_size
      lidar_range: *cav_lidar

    height_compression:
      feature_num: 256

    base_bev_backbone:
      layer_nums: [5, 5]
      layer_strides: [1, 2]
      num_filters: [128, 256]
      upsample_strides: [1, 2]
      num_upsample_filter: [256, 256]

    anchor_num: *achor_num

loss:
  core_method: chamfer_loss
  args:
    chamfer_weight: 1.0
    pc_num_weight: 0.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
    core_method: cosineannealwarm #step, multistep, Exponential and cosineannealwarm support
    epoches: *epoches
    warmup_lr: 2e-4
    warmup_epoches: 10
    lr_min: 2e-5
